[tool.poetry]
name = "escola-api"
version = "1.0.0"
description = "API Flask para sistema de gestao escolar"
authors = ["Fabio Bara"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0"
psycopg2-binary = "^2.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
